### ISSUE TITLE
Add graphs to dashboard

### ISSUE THREAD

**Issue by OwenCross289** [OwenCross289/ECM3440#21]

**Comment by exe-je437** [comment]
Inclined to try [Ant Blazor](https://github.com/ant-design-blazor/ant-design-charts-blazor) when I get time. Gets [good reviews](https://www.reddit.com/r/Blazor/comments/qvzbdd/what_is_the_best_library_for_creating_graphs/) and seems really easy to create a simple line chart. Happy to demo before PR
